# Generated by Django 4.2.18 on 2025-05-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'CSS'), (3, 'JavaScript'), (4, 'TypeScript'), (5, 'Java'), (6, 'C'), (7, 'C#'), (8, 'C++'), (9, 'Go')]),
        ),
    ]
